# Calculate the MAP and EXP factors
CalcPANSS <- function(PANSS){
  PANSS$Total <- (PANSS$PANSS1 + PANSS$PANSS2 + PANSS$PANSS3 + PANSS$PANSS4 + PANSS$PANSS5 + PANSS$PANSS6 + PANSS$PANSS7 + PANSS$PANSS8 +
                    PANSS$PANSS9 + PANSS$PANSS10 + PANSS$PANSS11 + PANSS$PANSS12 + PANSS$PANSS13 + PANSS$PANSS14 + PANSS$PANSS15 + PANSS$PANSS16
                  + PANSS$PANSS17 + PANSS$PANSS18 + PANSS$PANSS19 + PANSS$PANSS20 + PANSS$PANSS21 + PANSS$PANSS22 + PANSS$PANSS23
                  + PANSS$PANSS24 + PANSS$PANSS25 + PANSS$PANSS26 + PANSS$PANSS27 + PANSS$PANSS28 + PANSS$PANSS29 + PANSS$PANSS30)

  PANSS$Neg_Total <- (PANSS$PANSS8 + PANSS$PANSS9 + PANSS$PANSS10 + PANSS$PANSS11 + PANSS$PANSS12 + PANSS$PANSS13 + PANSS$PANSS14)

  PANSS$Pos_Total <- (PANSS$PANSS1 + PANSS$PANSS2 + PANSS$PANSS3 + PANSS$PANSS4 + PANSS$PANSS5 + PANSS$PANSS6 + PANSS$PANSS7)

  PANSS$Gen_Total <- (PANSS$PANSS15 + PANSS$PANSS16 + PANSS$PANSS17 + PANSS$PANSS18 + PANSS$PANSS19 + PANSS$PANSS20 + PANSS$PANSS21
                         + PANSS$PANSS22 + PANSS$PANSS23 + PANSS$PANSS24 + PANSS$PANSS25 + PANSS$PANSS26 + PANSS$PANSS27 + PANSS$PANSS28
                         + PANSS$PANSS29 + PANSS$PANSS30)

  PANSS$EXP_Total <- (PANSS$PANSS8*.749)+(PANSS$PANSS10*.696)+(PANSS$PANSS13*.783)+(PANSS$PANSS21*.744)

  PANSS$MAP_Total <- (PANSS$PANSS9*.666)+(PANSS$PANSS11*.799)+(PANSS$PANSS30*.866)

  return(as.data.frame(PANSS))
}
